//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 03:36:53 PM IST 
//


package rispl.jaxb.customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Represents a single business's information. In this case, setting
 * 			any person attributes, like FirstName would be for the company's
 * 			contact.
 * 		
 * 
 * <p>Java class for BusinessCustomer_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessCustomer_type">
 *   &lt;complexContent>
 *     &lt;extension base="{}Customer_type">
 *       &lt;attribute name="CompanyName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TaxExemptionCertificate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExceptionReason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessCustomer_type")
public class BusinessCustomerType
    extends CustomerType
{

    @XmlAttribute(name = "CompanyName", required = true)
    protected String companyName;
    @XmlAttribute(name = "TaxExemptionCertificate")
    protected String taxExemptionCertificate;
    @XmlAttribute(name = "ExceptionReason")
    protected String exceptionReason;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the taxExemptionCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptionCertificate() {
        return taxExemptionCertificate;
    }

    /**
     * Sets the value of the taxExemptionCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptionCertificate(String value) {
        this.taxExemptionCertificate = value;
    }

    /**
     * Gets the value of the exceptionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExceptionReason() {
        return exceptionReason;
    }

    /**
     * Sets the value of the exceptionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExceptionReason(String value) {
        this.exceptionReason = value;
    }

}
