//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 03:36:53 PM IST 
//


package rispl.jaxb.customer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rispl.jaxb.customer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rispl.jaxb.customer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link LocalizedNameDescriptionType }
     * 
     */
    public LocalizedNameDescriptionType createLocalizedNameDescriptionType() {
        return new LocalizedNameDescriptionType();
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link LocalizedMessageDescriptionType }
     * 
     */
    public LocalizedMessageDescriptionType createLocalizedMessageDescriptionType() {
        return new LocalizedMessageDescriptionType();
    }

    /**
     * Create an instance of {@link CustomerGroupIDType }
     * 
     */
    public CustomerGroupIDType createCustomerGroupIDType() {
        return new CustomerGroupIDType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link LocalizedItemSizeDescriptionType }
     * 
     */
    public LocalizedItemSizeDescriptionType createLocalizedItemSizeDescriptionType() {
        return new LocalizedItemSizeDescriptionType();
    }

    /**
     * Create an instance of {@link TelephoneType }
     * 
     */
    public TelephoneType createTelephoneType() {
        return new TelephoneType();
    }

    /**
     * Create an instance of {@link NameDescriptionType }
     * 
     */
    public NameDescriptionType createNameDescriptionType() {
        return new NameDescriptionType();
    }

    /**
     * Create an instance of {@link CustomerGroupType }
     * 
     */
    public CustomerGroupType createCustomerGroupType() {
        return new CustomerGroupType();
    }

    /**
     * Create an instance of {@link CustomerImport }
     * 
     */
    public CustomerImport createCustomerImport() {
        return new CustomerImport();
    }

    /**
     * Create an instance of {@link LocalizedDescriptionType }
     * 
     */
    public LocalizedDescriptionType createLocalizedDescriptionType() {
        return new LocalizedDescriptionType();
    }

    /**
     * Create an instance of {@link PricingGroup }
     * 
     */
    public PricingGroup createPricingGroup() {
        return new PricingGroup();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link BusinessCustomerType }
     * 
     */
    public BusinessCustomerType createBusinessCustomerType() {
        return new BusinessCustomerType();
    }

}
