//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 02:52:33 PM IST 
//


package rispl.jaxb.item;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rsi.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rsi.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ColorType }
     * 
     */
    public ColorType createColorType() {
        return new ColorType();
    }

    /**
     * Create an instance of {@link MerchandiseClassificationType }
     * 
     */
    public MerchandiseClassificationType createMerchandiseClassificationType() {
        return new MerchandiseClassificationType();
    }

    /**
     * Create an instance of {@link LocalizedDescriptionType }
     * 
     */
    public LocalizedDescriptionType createLocalizedDescriptionType() {
        return new LocalizedDescriptionType();
    }

    /**
     * Create an instance of {@link RegularPriceType }
     * 
     */
    public RegularPriceType createRegularPriceType() {
        return new RegularPriceType();
    }

    /**
     * Create an instance of {@link MerchandiseHierarchyType }
     * 
     */
    public MerchandiseHierarchyType createMerchandiseHierarchyType() {
        return new MerchandiseHierarchyType();
    }

    /**
     * Create an instance of {@link UOMType }
     * 
     */
    public UOMType createUOMType() {
        return new UOMType();
    }

    /**
     * Create an instance of {@link POSIdentityType }
     * 
     */
    public POSIdentityType createPOSIdentityType() {
        return new POSIdentityType();
    }

    /**
     * Create an instance of {@link RetailStoreItemType }
     * 
     */
    public RetailStoreItemType createRetailStoreItemType() {
        return new RetailStoreItemType();
    }

    /**
     * Create an instance of {@link LocalizedItemSizeDescriptionType }
     * 
     */
    public LocalizedItemSizeDescriptionType createLocalizedItemSizeDescriptionType() {
        return new LocalizedItemSizeDescriptionType();
    }

    /**
     * Create an instance of {@link SizeType }
     * 
     */
    public SizeType createSizeType() {
        return new SizeType();
    }

    /**
     * Create an instance of {@link ItemImport }
     * 
     */
    public ItemImport createItemImport() {
        return new ItemImport();
    }

    /**
     * Create an instance of {@link SupplierType }
     * 
     */
    public SupplierType createSupplierType() {
        return new SupplierType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link PreloadDataType }
     * 
     */
    public PreloadDataType createPreloadDataType() {
        return new PreloadDataType();
    }

    /**
     * Create an instance of {@link StyleType }
     * 
     */
    public StyleType createStyleType() {
        return new StyleType();
    }

    /**
     * Create an instance of {@link LocalizedNameDescriptionType }
     * 
     */
    public LocalizedNameDescriptionType createLocalizedNameDescriptionType() {
        return new LocalizedNameDescriptionType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link LocalizedMessageDescriptionType }
     * 
     */
    public LocalizedMessageDescriptionType createLocalizedMessageDescriptionType() {
        return new LocalizedMessageDescriptionType();
    }

    /**
     * Create an instance of {@link DisplayMessageType }
     * 
     */
    public DisplayMessageType createDisplayMessageType() {
        return new DisplayMessageType();
    }

    /**
     * Create an instance of {@link NameDescriptionType }
     * 
     */
    public NameDescriptionType createNameDescriptionType() {
        return new NameDescriptionType();
    }

    /**
     * Create an instance of {@link ManufacturerType }
     * 
     */
    public ManufacturerType createManufacturerType() {
        return new ManufacturerType();
    }

    /**
     * Create an instance of {@link ItemLevelMessagesType }
     * 
     */
    public ItemLevelMessagesType createItemLevelMessagesType() {
        return new ItemLevelMessagesType();
    }

    /**
     * Create an instance of {@link RelatedItemAssociationType }
     * 
     */
    public RelatedItemAssociationType createRelatedItemAssociationType() {
        return new RelatedItemAssociationType();
    }

    /**
     * Create an instance of {@link UINLabelType }
     * 
     */
    public UINLabelType createUINLabelType() {
        return new UINLabelType();
    }

}
