//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 02:52:33 PM IST 
//


package rispl.jaxb.item;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Multiple POSIdentity elements may be specified when different
 *             UPCs apply to the same item.
 *         
 * 
 * <p>Java class for POSIdentity_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POSIdentity_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ChangeType" type="{}ChangeType_subtype" default="ADD" />
 *       &lt;attribute name="POSItemID" use="required" type="{}ID_type" />
 *       &lt;attribute name="UPC" type="{}ID_type" />
 *       &lt;attribute name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ManufacturerID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="QuantityModifiable" default="Optional">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Required"/>
 *             &lt;enumeration value="Prohibited"/>
 *             &lt;enumeration value="Optional"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Returnable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PriceEntryRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="PriceModifiable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AllowCouponMultiply" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ElectronicCoupon" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="CouponRestricted" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SpecialOrderEligible" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EmployeeDiscountAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="MinimumSaleUnitCount" type="{http://www.w3.org/2001/XMLSchema}decimal" default="1.0" />
 *       &lt;attribute name="MaximumSaleUnitCount" type="{http://www.w3.org/2001/XMLSchema}decimal" default="-1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POSIdentity_type")
public class POSIdentityType {

    @XmlAttribute(name = "ChangeType")
    protected ChangeTypeSubtype changeType;
    @XmlAttribute(name = "POSItemID", required = true)
    protected String posItemID;
    @XmlAttribute(name = "UPC")
    protected String upc;
    @XmlAttribute(name = "SupplierID")
    protected String supplierID;
    @XmlAttribute(name = "ManufacturerID")
    protected Integer manufacturerID;
    @XmlAttribute(name = "QuantityModifiable")
    protected String quantityModifiable;
    @XmlAttribute(name = "Returnable")
    protected Boolean returnable;
    @XmlAttribute(name = "PriceEntryRequired")
    protected Boolean priceEntryRequired;
    @XmlAttribute(name = "PriceModifiable")
    protected Boolean priceModifiable;
    @XmlAttribute(name = "AllowCouponMultiply")
    protected Boolean allowCouponMultiply;
    @XmlAttribute(name = "ElectronicCoupon")
    protected Boolean electronicCoupon;
    @XmlAttribute(name = "CouponRestricted")
    protected Boolean couponRestricted;
    @XmlAttribute(name = "SpecialOrderEligible")
    protected Boolean specialOrderEligible;
    @XmlAttribute(name = "EmployeeDiscountAllowed")
    protected Boolean employeeDiscountAllowed;
    @XmlAttribute(name = "MinimumSaleUnitCount")
    protected BigDecimal minimumSaleUnitCount;
    @XmlAttribute(name = "MaximumSaleUnitCount")
    protected BigDecimal maximumSaleUnitCount;

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeSubtype }
     *     
     */
    public ChangeTypeSubtype getChangeType() {
        if (changeType == null) {
            return ChangeTypeSubtype.ADD;
        } else {
            return changeType;
        }
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeSubtype }
     *     
     */
    public void setChangeType(ChangeTypeSubtype value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the posItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSItemID() {
        return posItemID;
    }

    /**
     * Sets the value of the posItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSItemID(String value) {
        this.posItemID = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPC() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPC(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the supplierID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierID() {
        return supplierID;
    }

    /**
     * Sets the value of the supplierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierID(String value) {
        this.supplierID = value;
    }

    /**
     * Gets the value of the manufacturerID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getManufacturerID() {
        return manufacturerID;
    }

    /**
     * Sets the value of the manufacturerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setManufacturerID(Integer value) {
        this.manufacturerID = value;
    }

    /**
     * Gets the value of the quantityModifiable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityModifiable() {
        if (quantityModifiable == null) {
            return "Optional";
        } else {
            return quantityModifiable;
        }
    }

    /**
     * Sets the value of the quantityModifiable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityModifiable(String value) {
        this.quantityModifiable = value;
    }

    /**
     * Gets the value of the returnable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnable() {
        return returnable;
    }

    /**
     * Sets the value of the returnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnable(Boolean value) {
        this.returnable = value;
    }

    /**
     * Gets the value of the priceEntryRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPriceEntryRequired() {
        if (priceEntryRequired == null) {
            return false;
        } else {
            return priceEntryRequired;
        }
    }

    /**
     * Sets the value of the priceEntryRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriceEntryRequired(Boolean value) {
        this.priceEntryRequired = value;
    }

    /**
     * Gets the value of the priceModifiable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPriceModifiable() {
        return priceModifiable;
    }

    /**
     * Sets the value of the priceModifiable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriceModifiable(Boolean value) {
        this.priceModifiable = value;
    }

    /**
     * Gets the value of the allowCouponMultiply property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowCouponMultiply() {
        return allowCouponMultiply;
    }

    /**
     * Sets the value of the allowCouponMultiply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowCouponMultiply(Boolean value) {
        this.allowCouponMultiply = value;
    }

    /**
     * Gets the value of the electronicCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isElectronicCoupon() {
        return electronicCoupon;
    }

    /**
     * Sets the value of the electronicCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setElectronicCoupon(Boolean value) {
        this.electronicCoupon = value;
    }

    /**
     * Gets the value of the couponRestricted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCouponRestricted() {
        return couponRestricted;
    }

    /**
     * Sets the value of the couponRestricted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCouponRestricted(Boolean value) {
        this.couponRestricted = value;
    }

    /**
     * Gets the value of the specialOrderEligible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSpecialOrderEligible() {
        return specialOrderEligible;
    }

    /**
     * Sets the value of the specialOrderEligible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSpecialOrderEligible(Boolean value) {
        this.specialOrderEligible = value;
    }

    /**
     * Gets the value of the employeeDiscountAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEmployeeDiscountAllowed() {
        if (employeeDiscountAllowed == null) {
            return true;
        } else {
            return employeeDiscountAllowed;
        }
    }

    /**
     * Sets the value of the employeeDiscountAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmployeeDiscountAllowed(Boolean value) {
        this.employeeDiscountAllowed = value;
    }

    /**
     * Gets the value of the minimumSaleUnitCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimumSaleUnitCount() {
        if (minimumSaleUnitCount == null) {
            return new BigDecimal("1.0");
        } else {
            return minimumSaleUnitCount;
        }
    }

    /**
     * Sets the value of the minimumSaleUnitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimumSaleUnitCount(BigDecimal value) {
        this.minimumSaleUnitCount = value;
    }

    /**
     * Gets the value of the maximumSaleUnitCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumSaleUnitCount() {
        if (maximumSaleUnitCount == null) {
            return new BigDecimal("-1.0");
        } else {
            return maximumSaleUnitCount;
        }
    }

    /**
     * Sets the value of the maximumSaleUnitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumSaleUnitCount(BigDecimal value) {
        this.maximumSaleUnitCount = value;
    }

}
