//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 02:52:33 PM IST 
//


package rispl.jaxb.item;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreloadData_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreloadData_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Color" type="{}Color_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Size" type="{}Size_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Style" type="{}Style_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UOM" type="{}UOM_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Manufacturer" type="{}Manufacturer_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MerchandiseClassification" type="{}MerchandiseClassification_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Supplier" type="{}Supplier_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Message" type="{}DisplayMessage_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreloadData_type", propOrder = {
    "color",
    "size",
    "style",
    "uom",
    "manufacturer",
    "merchandiseClassification",
    "supplier",
    "message"
})
public class PreloadDataType {

    @XmlElement(name = "Color")
    protected List<ColorType> color;
    @XmlElement(name = "Size")
    protected List<SizeType> size;
    @XmlElement(name = "Style")
    protected List<StyleType> style;
    @XmlElement(name = "UOM")
    protected List<UOMType> uom;
    @XmlElement(name = "Manufacturer")
    protected List<ManufacturerType> manufacturer;
    @XmlElement(name = "MerchandiseClassification")
    protected List<MerchandiseClassificationType> merchandiseClassification;
    @XmlElement(name = "Supplier")
    protected List<SupplierType> supplier;
    @XmlElement(name = "Message")
    protected List<DisplayMessageType> message;

    /**
     * Gets the value of the color property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the color property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColorType }
     * 
     * 
     */
    public List<ColorType> getColor() {
        if (color == null) {
            color = new ArrayList<ColorType>();
        }
        return this.color;
    }

    /**
     * Gets the value of the size property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the size property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SizeType }
     * 
     * 
     */
    public List<SizeType> getSize() {
        if (size == null) {
            size = new ArrayList<SizeType>();
        }
        return this.size;
    }

    /**
     * Gets the value of the style property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the style property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StyleType }
     * 
     * 
     */
    public List<StyleType> getStyle() {
        if (style == null) {
            style = new ArrayList<StyleType>();
        }
        return this.style;
    }

    /**
     * Gets the value of the uom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUOM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UOMType }
     * 
     * 
     */
    public List<UOMType> getUOM() {
        if (uom == null) {
            uom = new ArrayList<UOMType>();
        }
        return this.uom;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manufacturer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManufacturer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerType }
     * 
     * 
     */
    public List<ManufacturerType> getManufacturer() {
        if (manufacturer == null) {
            manufacturer = new ArrayList<ManufacturerType>();
        }
        return this.manufacturer;
    }

    /**
     * Gets the value of the merchandiseClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the merchandiseClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMerchandiseClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MerchandiseClassificationType }
     * 
     * 
     */
    public List<MerchandiseClassificationType> getMerchandiseClassification() {
        if (merchandiseClassification == null) {
            merchandiseClassification = new ArrayList<MerchandiseClassificationType>();
        }
        return this.merchandiseClassification;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplierType }
     * 
     * 
     */
    public List<SupplierType> getSupplier() {
        if (supplier == null) {
            supplier = new ArrayList<SupplierType>();
        }
        return this.supplier;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayMessageType }
     * 
     * 
     */
    public List<DisplayMessageType> getMessage() {
        if (message == null) {
            message = new ArrayList<DisplayMessageType>();
        }
        return this.message;
    }

}
