//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 02:52:33 PM IST 
//


package rispl.jaxb.item;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Item-location information. This element requires a child element to
 *             specify a store id. This element can be repeated if this same info
 *             should belong to multiple stores. The price element may be repeated
 *             to support foreign currency by specifying differnt currency codes.
 * 
 *             Even though RegularPrice can be defined with different currency code,
 *             Currently only the price in base currency is supported. If a list of
 *             REgularPrice elements used, the very last one will be picked up.
 *         
 * 
 * <p>Java class for RetailStoreItem_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetailStoreItem_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RetailStoreID" type="{}RetailStoreId_type" maxOccurs="unbounded"/>
 *         &lt;element name="RegularPrice" type="{}RegularPrice_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="POSIdentity" type="{}POSIdentity_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ChangeType" type="{}ChangeType_subtype" default="ADD" />
 *       &lt;attribute name="TaxGroup" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="VatCode" type="{}Code_type" />
 *       &lt;attribute name="AgeRestrictionId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TemplateId" default="*DEFAULT">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="8"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetailStoreItem_type", propOrder = {
    "retailStoreID",
    "regularPrice",
    "posIdentity"
})
public class RetailStoreItemType {

    @XmlElement(name = "RetailStoreID", required = true)
    protected List<String> retailStoreID;
    @XmlElement(name = "RegularPrice")
    protected List<RegularPriceType> regularPrice;
    @XmlElement(name = "POSIdentity")
    protected List<POSIdentityType> posIdentity;
    @XmlAttribute(name = "ChangeType")
    protected ChangeTypeSubtype changeType;
    @XmlAttribute(name = "TaxGroup")
    protected Integer taxGroup;
    @XmlAttribute(name = "VatCode")
    protected String vatCode;
    @XmlAttribute(name = "AgeRestrictionId")
    protected Integer ageRestrictionId;
    @XmlAttribute(name = "TemplateId")
    protected String templateId;

    /**
     * Gets the value of the retailStoreID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retailStoreID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetailStoreID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRetailStoreID() {
        if (retailStoreID == null) {
            retailStoreID = new ArrayList<String>();
        }
        return this.retailStoreID;
    }

    /**
     * Gets the value of the regularPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regularPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegularPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegularPriceType }
     * 
     * 
     */
    public List<RegularPriceType> getRegularPrice() {
        if (regularPrice == null) {
            regularPrice = new ArrayList<RegularPriceType>();
        }
        return this.regularPrice;
    }

    /**
     * Gets the value of the posIdentity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the posIdentity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOSIdentity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POSIdentityType }
     * 
     * 
     */
    public List<POSIdentityType> getPOSIdentity() {
        if (posIdentity == null) {
            posIdentity = new ArrayList<POSIdentityType>();
        }
        return this.posIdentity;
    }

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeSubtype }
     *     
     */
    public ChangeTypeSubtype getChangeType() {
        if (changeType == null) {
            return ChangeTypeSubtype.ADD;
        } else {
            return changeType;
        }
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeSubtype }
     *     
     */
    public void setChangeType(ChangeTypeSubtype value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the taxGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTaxGroup() {
        return taxGroup;
    }

    /**
     * Sets the value of the taxGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTaxGroup(Integer value) {
        this.taxGroup = value;
    }

    /**
     * Gets the value of the vatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatCode() {
        return vatCode;
    }

    /**
     * Sets the value of the vatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatCode(String value) {
        this.vatCode = value;
    }

    /**
     * Gets the value of the ageRestrictionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeRestrictionId() {
        return ageRestrictionId;
    }

    /**
     * Sets the value of the ageRestrictionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeRestrictionId(Integer value) {
        this.ageRestrictionId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateId() {
        if (templateId == null) {
            return "*DEFAULT";
        } else {
            return templateId;
        }
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateId(String value) {
        this.templateId = value;
    }

}
