//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 02:52:33 PM IST 
//


package rispl.jaxb.item;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Size_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Size_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocalizedSizeData" type="{}LocalizedItemSizeDescription_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ChangeType" type="{}ChangeType_subtype" default="UPS" />
 *       &lt;attribute name="Code" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ProportionDesc" type="{}Description_type" />
 *       &lt;attribute name="TypeDesc" type="{}Name_type" />
 *       &lt;attribute name="ActualSizeCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{}Code_type">
 *             &lt;pattern value="\d+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TableName" type="{}Name_type" />
 *       &lt;attribute name="TableCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="1"/>
 *             &lt;pattern value="\d"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TableDesc" type="{}Description_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Size_type", propOrder = {
    "localizedSizeData"
})
public class SizeType {

    @XmlElement(name = "LocalizedSizeData")
    protected List<LocalizedItemSizeDescriptionType> localizedSizeData;
    @XmlAttribute(name = "ChangeType")
    protected ChangeTypeSubtype changeType;
    @XmlAttribute(name = "Code", required = true)
    protected String code;
    @XmlAttribute(name = "ProportionDesc")
    protected String proportionDesc;
    @XmlAttribute(name = "TypeDesc")
    protected String typeDesc;
    @XmlAttribute(name = "ActualSizeCode")
    protected String actualSizeCode;
    @XmlAttribute(name = "TableName")
    protected String tableName;
    @XmlAttribute(name = "TableCode")
    protected String tableCode;
    @XmlAttribute(name = "TableDesc")
    protected String tableDesc;

    /**
     * Gets the value of the localizedSizeData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedSizeData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedSizeData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedItemSizeDescriptionType }
     * 
     * 
     */
    public List<LocalizedItemSizeDescriptionType> getLocalizedSizeData() {
        if (localizedSizeData == null) {
            localizedSizeData = new ArrayList<LocalizedItemSizeDescriptionType>();
        }
        return this.localizedSizeData;
    }

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeSubtype }
     *     
     */
    public ChangeTypeSubtype getChangeType() {
        if (changeType == null) {
            return ChangeTypeSubtype.UPS;
        } else {
            return changeType;
        }
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeSubtype }
     *     
     */
    public void setChangeType(ChangeTypeSubtype value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the proportionDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProportionDesc() {
        return proportionDesc;
    }

    /**
     * Sets the value of the proportionDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProportionDesc(String value) {
        this.proportionDesc = value;
    }

    /**
     * Gets the value of the typeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * Sets the value of the typeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeDesc(String value) {
        this.typeDesc = value;
    }

    /**
     * Gets the value of the actualSizeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualSizeCode() {
        return actualSizeCode;
    }

    /**
     * Sets the value of the actualSizeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualSizeCode(String value) {
        this.actualSizeCode = value;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

    /**
     * Gets the value of the tableCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableCode() {
        return tableCode;
    }

    /**
     * Sets the value of the tableCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableCode(String value) {
        this.tableCode = value;
    }

    /**
     * Gets the value of the tableDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableDesc() {
        return tableDesc;
    }

    /**
     * Sets the value of the tableDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableDesc(String value) {
        this.tableDesc = value;
    }

}
