//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 05:37:53 PM IST 
//


package rispl.jaxb.employee;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 			Represents a single employee's information.
 * 		
 * 
 * <p>Java class for Employee_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Employee_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChangeType" type="{}ChangeType_type"/>
 *         &lt;element name="EmployeeID" type="{}EmployeeID_type"/>
 *         &lt;element name="EmployeeFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployeeLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployeeMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployeeFullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployeeSSN" type="{}SSN_type" minOccurs="0"/>
 *         &lt;element name="EmployeeRole" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PartyID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusCode" type="{}StatusCode_type" minOccurs="0"/>
 *         &lt;element name="Locale" type="{}ID_type" minOccurs="0"/>
 *         &lt;element name="MerchandiseAssociation" type="{}MerchandiseAssociation_type" minOccurs="0"/>
 *         &lt;element name="EmployeeAccess" type="{}EmployeeAccess_type" minOccurs="0"/>
 *         &lt;element name="EmployeeType" type="{}StatusCode_type"/>
 *         &lt;element name="NumberDaysValid" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TempEmployeeExpirationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="EmployeeStoreOrHierarchyAssn" type="{}EmployeeStoreOrHierarchyAssn_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Employee_type", propOrder = {
    "changeType",
    "employeeID",
    "employeeFirstName",
    "employeeLastName",
    "employeeMiddleName",
    "employeeFullName",
    "employeeSSN",
    "employeeRole",
    "partyID",
    "email",
    "statusCode",
    "locale",
    "merchandiseAssociation",
    "employeeAccess",
    "employeeType",
    "numberDaysValid",
    "tempEmployeeExpirationDate",
    "employeeStoreOrHierarchyAssn"
})
public class EmployeeType {

    @XmlElement(name = "ChangeType", required = true, defaultValue = "ADD")
    protected ChangeTypeType changeType;
    @XmlElement(name = "EmployeeID", required = true)
    protected String employeeID;
    @XmlElement(name = "EmployeeFirstName")
    protected String employeeFirstName;
    @XmlElement(name = "EmployeeLastName")
    protected String employeeLastName;
    @XmlElement(name = "EmployeeMiddleName")
    protected String employeeMiddleName;
    @XmlElement(name = "EmployeeFullName")
    protected String employeeFullName;
    @XmlElement(name = "EmployeeSSN")
    protected String employeeSSN;
    @XmlElement(name = "EmployeeRole")
    protected String employeeRole;
    @XmlElement(name = "PartyID")
    protected Integer partyID;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "StatusCode")
    protected String statusCode;
    @XmlElement(name = "Locale")
    protected String locale;
    @XmlElement(name = "MerchandiseAssociation")
    protected MerchandiseAssociationType merchandiseAssociation;
    @XmlElement(name = "EmployeeAccess")
    protected EmployeeAccessType employeeAccess;
    @XmlElement(name = "EmployeeType", required = true)
    protected String employeeType;
    @XmlElement(name = "NumberDaysValid")
    protected Integer numberDaysValid;
    @XmlElement(name = "TempEmployeeExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tempEmployeeExpirationDate;
    @XmlElement(name = "EmployeeStoreOrHierarchyAssn")
    protected List<EmployeeStoreOrHierarchyAssnType> employeeStoreOrHierarchyAssn;

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeType }
     *     
     */
    public ChangeTypeType getChangeType() {
        return changeType;
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeType }
     *     
     */
    public void setChangeType(ChangeTypeType value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the employeeFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeFirstName() {
        return employeeFirstName;
    }

    /**
     * Sets the value of the employeeFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeFirstName(String value) {
        this.employeeFirstName = value;
    }

    /**
     * Gets the value of the employeeLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeLastName() {
        return employeeLastName;
    }

    /**
     * Sets the value of the employeeLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeLastName(String value) {
        this.employeeLastName = value;
    }

    /**
     * Gets the value of the employeeMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeMiddleName() {
        return employeeMiddleName;
    }

    /**
     * Sets the value of the employeeMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeMiddleName(String value) {
        this.employeeMiddleName = value;
    }

    /**
     * Gets the value of the employeeFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeFullName() {
        return employeeFullName;
    }

    /**
     * Sets the value of the employeeFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeFullName(String value) {
        this.employeeFullName = value;
    }

    /**
     * Gets the value of the employeeSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeSSN() {
        return employeeSSN;
    }

    /**
     * Sets the value of the employeeSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeSSN(String value) {
        this.employeeSSN = value;
    }

    /**
     * Gets the value of the employeeRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeRole() {
        return employeeRole;
    }

    /**
     * Sets the value of the employeeRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeRole(String value) {
        this.employeeRole = value;
    }

    /**
     * Gets the value of the partyID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPartyID() {
        return partyID;
    }

    /**
     * Sets the value of the partyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPartyID(Integer value) {
        this.partyID = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the merchandiseAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link MerchandiseAssociationType }
     *     
     */
    public MerchandiseAssociationType getMerchandiseAssociation() {
        return merchandiseAssociation;
    }

    /**
     * Sets the value of the merchandiseAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchandiseAssociationType }
     *     
     */
    public void setMerchandiseAssociation(MerchandiseAssociationType value) {
        this.merchandiseAssociation = value;
    }

    /**
     * Gets the value of the employeeAccess property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeAccessType }
     *     
     */
    public EmployeeAccessType getEmployeeAccess() {
        return employeeAccess;
    }

    /**
     * Sets the value of the employeeAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeAccessType }
     *     
     */
    public void setEmployeeAccess(EmployeeAccessType value) {
        this.employeeAccess = value;
    }

    /**
     * Gets the value of the employeeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeType() {
        return employeeType;
    }

    /**
     * Sets the value of the employeeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeType(String value) {
        this.employeeType = value;
    }

    /**
     * Gets the value of the numberDaysValid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberDaysValid() {
        return numberDaysValid;
    }

    /**
     * Sets the value of the numberDaysValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberDaysValid(Integer value) {
        this.numberDaysValid = value;
    }

    /**
     * Gets the value of the tempEmployeeExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTempEmployeeExpirationDate() {
        return tempEmployeeExpirationDate;
    }

    /**
     * Sets the value of the tempEmployeeExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTempEmployeeExpirationDate(XMLGregorianCalendar value) {
        this.tempEmployeeExpirationDate = value;
    }

    /**
     * Gets the value of the employeeStoreOrHierarchyAssn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employeeStoreOrHierarchyAssn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmployeeStoreOrHierarchyAssn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmployeeStoreOrHierarchyAssnType }
     * 
     * 
     */
    public List<EmployeeStoreOrHierarchyAssnType> getEmployeeStoreOrHierarchyAssn() {
        if (employeeStoreOrHierarchyAssn == null) {
            employeeStoreOrHierarchyAssn = new ArrayList<EmployeeStoreOrHierarchyAssnType>();
        }
        return this.employeeStoreOrHierarchyAssn;
    }
    
    //for email id
    public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

}
