//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 05:37:53 PM IST 
//


package rispl.jaxb.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmployeeHierarchyAssn_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployeeHierarchyAssn_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NodeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NodeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StoreGroupFunctionID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployeeHierarchyAssn_type", propOrder = {
    "nodeID",
    "nodeType",
    "storeGroupFunctionID"
})
public class EmployeeHierarchyAssnType {

    @XmlElement(name = "NodeID", required = true)
    protected String nodeID;
    @XmlElement(name = "NodeType", required = true)
    protected String nodeType;
    @XmlElement(name = "StoreGroupFunctionID")
    protected int storeGroupFunctionID;

    /**
     * Gets the value of the nodeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeID() {
        return nodeID;
    }

    /**
     * Sets the value of the nodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeID(String value) {
        this.nodeID = value;
    }

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeType(String value) {
        this.nodeType = value;
    }

    /**
     * Gets the value of the storeGroupFunctionID property.
     * 
     */
    public int getStoreGroupFunctionID() {
        return storeGroupFunctionID;
    }

    /**
     * Sets the value of the storeGroupFunctionID property.
     * 
     */
    public void setStoreGroupFunctionID(int value) {
        this.storeGroupFunctionID = value;
    }

}
