//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 05:37:53 PM IST 
//


package rispl.jaxb.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 			Holds all information regarding access to the system.
 * 		
 * 
 * <p>Java class for EmployeeAccess_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployeeAccess_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmployeeLoginID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccessPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorkGroupID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EmployeeAltID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NewPasswordRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="PasswordCreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="PasswordHistory" type="{}PasswordHistory_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployeeAccess_type", propOrder = {
    "employeeLoginID",
    "accessPassword",
    "workGroupID",
    "employeeAltID",
    "newPasswordRequired",
    "passwordCreationDate",
    "passwordHistory"
})
public class EmployeeAccessType {

    @XmlElement(name = "EmployeeLoginID", required = true)
    protected String employeeLoginID;
    @XmlElement(name = "AccessPassword", required = true)
    protected String accessPassword;
    @XmlElement(name = "WorkGroupID")
    protected int workGroupID;
    @XmlElement(name = "EmployeeAltID")
    protected String employeeAltID;
    @XmlElement(name = "NewPasswordRequired")
    protected boolean newPasswordRequired;
    @XmlElement(name = "PasswordCreationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar passwordCreationDate;
    @XmlElement(name = "PasswordHistory")
    protected PasswordHistoryType passwordHistory;

    /**
     * Gets the value of the employeeLoginID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeLoginID() {
        return employeeLoginID;
    }

    /**
     * Sets the value of the employeeLoginID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeLoginID(String value) {
        this.employeeLoginID = value;
    }

    /**
     * Gets the value of the accessPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessPassword() {
        return accessPassword;
    }

    /**
     * Sets the value of the accessPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessPassword(String value) {
        this.accessPassword = value;
    }

    /**
     * Gets the value of the workGroupID property.
     * 
     */
    public int getWorkGroupID() {
        return workGroupID;
    }

    /**
     * Sets the value of the workGroupID property.
     * 
     */
    public void setWorkGroupID(int value) {
        this.workGroupID = value;
    }

    /**
     * Gets the value of the employeeAltID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeAltID() {
        return employeeAltID;
    }

    /**
     * Sets the value of the employeeAltID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeAltID(String value) {
        this.employeeAltID = value;
    }

    /**
     * Gets the value of the newPasswordRequired property.
     * 
     */
    public boolean isNewPasswordRequired() {
        return newPasswordRequired;
    }

    /**
     * Sets the value of the newPasswordRequired property.
     * 
     */
    public void setNewPasswordRequired(boolean value) {
        this.newPasswordRequired = value;
    }

    /**
     * Gets the value of the passwordCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPasswordCreationDate() {
        return passwordCreationDate;
    }

    /**
     * Sets the value of the passwordCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPasswordCreationDate(XMLGregorianCalendar value) {
        this.passwordCreationDate = value;
    }

    /**
     * Gets the value of the passwordHistory property.
     * 
     * @return
     *     possible object is
     *     {@link PasswordHistoryType }
     *     
     */
    public PasswordHistoryType getPasswordHistory() {
        return passwordHistory;
    }

    /**
     * Sets the value of the passwordHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link PasswordHistoryType }
     *     
     */
    public void setPasswordHistory(PasswordHistoryType value) {
        this.passwordHistory = value;
    }

}
