//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 05:37:53 PM IST 
//


package rispl.jaxb.employee;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EmployeeImport_QNAME = new QName("", "EmployeeImport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeeStoreOrHierarchyAssnType }
     * 
     */
    public EmployeeStoreOrHierarchyAssnType createEmployeeStoreOrHierarchyAssnType() {
        return new EmployeeStoreOrHierarchyAssnType();
    }

    /**
     * Create an instance of {@link NameDescriptionType }
     * 
     */
    public NameDescriptionType createNameDescriptionType() {
        return new NameDescriptionType();
    }

    /**
     * Create an instance of {@link LocalizedItemSizeDescriptionType }
     * 
     */
    public LocalizedItemSizeDescriptionType createLocalizedItemSizeDescriptionType() {
        return new LocalizedItemSizeDescriptionType();
    }

    /**
     * Create an instance of {@link PasswordHistoryType }
     * 
     */
    public PasswordHistoryType createPasswordHistoryType() {
        return new PasswordHistoryType();
    }

    /**
     * Create an instance of {@link PasswordHistoryEntryType }
     * 
     */
    public PasswordHistoryEntryType createPasswordHistoryEntryType() {
        return new PasswordHistoryEntryType();
    }

    /**
     * Create an instance of {@link EmployeeHierarchyAssnType }
     * 
     */
    public EmployeeHierarchyAssnType createEmployeeHierarchyAssnType() {
        return new EmployeeHierarchyAssnType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link EmployeeImportType }
     * 
     */
    public EmployeeImportType createEmployeeImportType() {
        return new EmployeeImportType();
    }

    /**
     * Create an instance of {@link MerchandiseAssociationType }
     * 
     */
    public MerchandiseAssociationType createMerchandiseAssociationType() {
        return new MerchandiseAssociationType();
    }

    /**
     * Create an instance of {@link LocalizedDescriptionType }
     * 
     */
    public LocalizedDescriptionType createLocalizedDescriptionType() {
        return new LocalizedDescriptionType();
    }

    /**
     * Create an instance of {@link LocalizedNameDescriptionType }
     * 
     */
    public LocalizedNameDescriptionType createLocalizedNameDescriptionType() {
        return new LocalizedNameDescriptionType();
    }

    /**
     * Create an instance of {@link MerchIDType }
     * 
     */
    public MerchIDType createMerchIDType() {
        return new MerchIDType();
    }

    /**
     * Create an instance of {@link EmployeeAccessType }
     * 
     */
    public EmployeeAccessType createEmployeeAccessType() {
        return new EmployeeAccessType();
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link LocalizedMessageDescriptionType }
     * 
     */
    public LocalizedMessageDescriptionType createLocalizedMessageDescriptionType() {
        return new LocalizedMessageDescriptionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeeImportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmployeeImport")
    public JAXBElement<EmployeeImportType> createEmployeeImport(EmployeeImportType value) {
        return new JAXBElement<EmployeeImportType>(_EmployeeImport_QNAME, EmployeeImportType.class, null, value);
    }

}
