package rispl.db.model.claim;

import java.math.BigDecimal;
import java.sql.Timestamp;
import javax.annotation.Generated;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import rispl.dkart.services.entities.transaction.DkartReasonCodes;

@Generated(value="Dali", date="2018-01-09T13:30:28.533+0530")
@StaticMetamodel(ClaimTranLineItem.class)
public class ClaimTranLineItem_ {
	public static volatile SingularAttribute<ClaimTranLineItem, ClaimTranLineItemPK> id;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> aiLnItmOrg;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> aiLnItmRltd;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> accptClaimPrice;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> apprClaimPrice;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> apprClaimQty;
	public static volatile SingularAttribute<ClaimTranLineItem, String> dcDyBsnOrg;
	public static volatile SingularAttribute<ClaimTranLineItem, String> deItmLcl;
	public static volatile SingularAttribute<ClaimTranLineItem, String> deItmShrtRcpt;
	public static volatile SingularAttribute<ClaimTranLineItem, String> dkDptId;
	public static volatile SingularAttribute<ClaimTranLineItem, String> dkItmId;
	public static volatile SingularAttribute<ClaimTranLineItem, String> edSz;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> extnDscLnItm;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> extnLnItmRtn;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> feRstk;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flClrnc;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flDscEmAlw;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flFeRstk;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flItmDsc;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flItmDscDmg;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flItmPrcAdj;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flItmPrcOvrd;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flItmRtnQty;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flItmSzReq;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flMdfrPrc;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flRfdSv;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flRltdItmRm;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flRltdItmRtn;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flRtnMr;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flRtnPrh;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flRtrvdTrn;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flShpChg;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flSlsAsscMdf;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flTx;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flVdLnItm;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flVldSrzItm;
	public static volatile SingularAttribute<ClaimTranLineItem, String> flVldSrzItmExt;
	public static volatile SingularAttribute<ClaimTranLineItem, String> idCln;
	public static volatile SingularAttribute<ClaimTranLineItem, String> idItmMfUpc;
	public static volatile SingularAttribute<ClaimTranLineItem, String> idMrhrcGp;
	public static volatile SingularAttribute<ClaimTranLineItem, String> idNmbSrz;
	public static volatile SingularAttribute<ClaimTranLineItem, String> idNonRtvdOrgRcpt;
	public static volatile SingularAttribute<ClaimTranLineItem, String> idStrRtOrg;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> idnSlsAgRst;
	public static volatile SingularAttribute<ClaimTranLineItem, String> itemId;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> itmPrnPrc;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> itmTy;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> lineQnt;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> lineQntRtn;
	public static volatile SingularAttribute<ClaimTranLineItem, String> luEntrRtPrc;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> luKtHdrRfnId;
	public static volatile SingularAttribute<ClaimTranLineItem, String> luKtSt;
	public static volatile SingularAttribute<ClaimTranLineItem, String> luMthIdEnr;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> luPrcAdjRfnId;
	public static volatile SingularAttribute<ClaimTranLineItem, String> luPrcRtDrvn;
	public static volatile SingularAttribute<ClaimTranLineItem, String> mrLvHrc;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> orId;
	public static volatile SingularAttribute<ClaimTranLineItem, String> ordIdTrnOrg;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> ordLnItmSts;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> ovrdPrc;
	public static volatile SingularAttribute<ClaimTranLineItem, String> rcItmCndRtnMr;
	public static volatile SingularAttribute<ClaimTranLineItem, String> rcPrcOvrr;
	public static volatile SingularAttribute<ClaimTranLineItem, String> rcRfdSv;
	public static volatile SingularAttribute<ClaimTranLineItem, String> rcRtnMr;
	public static volatile SingularAttribute<ClaimTranLineItem, String> registryId;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> taxIncLnItmRtn;
	public static volatile SingularAttribute<ClaimTranLineItem, Timestamp> tsCrtRcrd;
	public static volatile SingularAttribute<ClaimTranLineItem, Timestamp> tsMdfRcrd;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> txGpId;
	public static volatile SingularAttribute<ClaimTranLineItem, String> uomSls;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> vatLnItmRtn;
	public static volatile SingularAttribute<ClaimTranLineItem, BigDecimal> whReceiveQty;
	public static volatile ListAttribute<ClaimTranLineItem, ClaimTranDscItm> claimTranDscItms;
	public static volatile SingularAttribute<ClaimTranLineItem, ClaimTranHeader> claimTranHeader;
	public static volatile SingularAttribute<ClaimTranLineItem, DkartReasonCodes> reasonCode;
	public static volatile SingularAttribute<ClaimTranLineItem, String> dispostionCode;
}
