//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 02:47:07 PM IST 
//


package rispl.jaxb.merchandisehierarchy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreloadData_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreloadData_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POSDepartment" type="{}POSDepartment_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MerchandiseGroup" type="{}MerchandiseGroup_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreloadData_type", propOrder = {
    "posDepartment",
    "merchandiseGroup"
})
public class PreloadDataType {

    @XmlElement(name = "POSDepartment")
    protected List<POSDepartmentType> posDepartment;
    @XmlElement(name = "MerchandiseGroup")
    protected List<MerchandiseGroupType> merchandiseGroup;

    /**
     * Gets the value of the posDepartment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the posDepartment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOSDepartment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POSDepartmentType }
     * 
     * 
     */
    public List<POSDepartmentType> getPOSDepartment() {
        if (posDepartment == null) {
            posDepartment = new ArrayList<POSDepartmentType>();
        }
        return this.posDepartment;
    }

    /**
     * Gets the value of the merchandiseGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the merchandiseGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMerchandiseGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MerchandiseGroupType }
     * 
     * 
     */
    public List<MerchandiseGroupType> getMerchandiseGroup() {
        if (merchandiseGroup == null) {
            merchandiseGroup = new ArrayList<MerchandiseGroupType>();
        }
        return this.merchandiseGroup;
    }

}
