//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 11:57:08 AM IST 
//


package rispl.jaxb.item.pricing;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemPriceCategory_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ItemPriceCategory_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Regular"/>
 *     &lt;enumeration value="Clearance"/>
 *     &lt;enumeration value="Both"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ItemPriceCategory_type")
@XmlEnum
public enum ItemPriceCategoryType {

    @XmlEnumValue("Regular")
    REGULAR("Regular"),
    @XmlEnumValue("Clearance")
    CLEARANCE("Clearance"),
    @XmlEnumValue("Both")
    BOTH("Both");
    private final String value;

    ItemPriceCategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ItemPriceCategoryType fromValue(String v) {
        for (ItemPriceCategoryType c: ItemPriceCategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
