//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 11:57:08 AM IST 
//


package rispl.jaxb.item.pricing;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rispl.jaxb.item.pricing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rispl.jaxb.item.pricing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocalizedNameDescriptionType }
     * 
     */
    public LocalizedNameDescriptionType createLocalizedNameDescriptionType() {
        return new LocalizedNameDescriptionType();
    }

    /**
     * Create an instance of {@link CancelItemType }
     * 
     */
    public CancelItemType createCancelItemType() {
        return new CancelItemType();
    }

    /**
     * Create an instance of {@link DiscountRuleType }
     * 
     */
    public DiscountRuleType createDiscountRuleType() {
        return new DiscountRuleType();
    }

    /**
     * Create an instance of {@link ClearanceResetEventType }
     * 
     */
    public ClearanceResetEventType createClearanceResetEventType() {
        return new ClearanceResetEventType();
    }

    /**
     * Create an instance of {@link LocalizedDescriptionType }
     * 
     */
    public LocalizedDescriptionType createLocalizedDescriptionType() {
        return new LocalizedDescriptionType();
    }

    /**
     * Create an instance of {@link LocalizedMessageDescriptionType }
     * 
     */
    public LocalizedMessageDescriptionType createLocalizedMessageDescriptionType() {
        return new LocalizedMessageDescriptionType();
    }

    /**
     * Create an instance of {@link PricingRuleType }
     * 
     */
    public PricingRuleType createPricingRuleType() {
        return new PricingRuleType();
    }

    /**
     * Create an instance of {@link ClearanceEventType }
     * 
     */
    public ClearanceEventType createClearanceEventType() {
        return new ClearanceEventType();
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link ThresholdsType }
     * 
     */
    public ThresholdsType createThresholdsType() {
        return new ThresholdsType();
    }

    /**
     * Create an instance of {@link CancelItemsType }
     * 
     */
    public CancelItemsType createCancelItemsType() {
        return new CancelItemsType();
    }

    /**
     * Create an instance of {@link PricingImport }
     * 
     */
    public PricingImport createPricingImport() {
        return new PricingImport();
    }

    /**
     * Create an instance of {@link NameDescriptionType }
     * 
     */
    public NameDescriptionType createNameDescriptionType() {
        return new NameDescriptionType();
    }

    /**
     * Create an instance of {@link ItemAndPriceType }
     * 
     */
    public ItemAndPriceType createItemAndPriceType() {
        return new ItemAndPriceType();
    }

    /**
     * Create an instance of {@link TargetsType.Target }
     * 
     */
    public TargetsType.Target createTargetsTypeTarget() {
        return new TargetsType.Target();
    }

    /**
     * Create an instance of {@link PricePromotionType }
     * 
     */
    public PricePromotionType createPricePromotionType() {
        return new PricePromotionType();
    }

    /**
     * Create an instance of {@link SourcesType.Source }
     * 
     */
    public SourcesType.Source createSourcesTypeSource() {
        return new SourcesType.Source();
    }

    /**
     * Create an instance of {@link ThresholdType }
     * 
     */
    public ThresholdType createThresholdType() {
        return new ThresholdType();
    }

    /**
     * Create an instance of {@link TargetsType }
     * 
     */
    public TargetsType createTargetsType() {
        return new TargetsType();
    }

    /**
     * Create an instance of {@link LocalizedItemSizeDescriptionType }
     * 
     */
    public LocalizedItemSizeDescriptionType createLocalizedItemSizeDescriptionType() {
        return new LocalizedItemSizeDescriptionType();
    }

    /**
     * Create an instance of {@link PriceChangeType }
     * 
     */
    public PriceChangeType createPriceChangeType() {
        return new PriceChangeType();
    }

    /**
     * Create an instance of {@link SourcesType }
     * 
     */
    public SourcesType createSourcesType() {
        return new SourcesType();
    }

}
