//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 11:57:08 AM IST 
//


package rispl.jaxb.item.pricing;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PricePromotion_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricePromotion_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="Name" type="{}LocalizedName_type" minOccurs="0"/>
 *             &lt;element name="Description" type="{}LocalizedDescription_type" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="LocalizedNameDescription" type="{}LocalizedNameDescription_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;group ref="{}DiscountTypeChoice" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="Item" type="{}ItemAndPrice_type" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="StoreID" type="{}RetailStoreId_type" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="CancelItems" type="{}CancelItems_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}PromotionComponentAttributes"/>
 *       &lt;attribute name="ChangeType" type="{}ChangeType_type" default="ADD" />
 *       &lt;attribute name="ItemPriceCategory" type="{}ItemPriceCategory_type" default="Regular" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="StartDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Type" use="required" type="{}PricePromotionType_type" />
 *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="TemplateType" default="*DEFAULT">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="8"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PricingGroupID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricePromotion_type", propOrder = {
    "name",
    "description",
    "localizedNameDescription",
    "discountPercent",
    "discountAmount",
    "newPrice",
    "item",
    "storeID",
    "cancelItems"
})
public class PricePromotionType {

    @XmlElement(name = "Name")
    protected LocalizedNameType name;
    @XmlElement(name = "Description")
    protected LocalizedDescriptionType description;
    @XmlElement(name = "LocalizedNameDescription")
    protected List<LocalizedNameDescriptionType> localizedNameDescription;
    @XmlElement(name = "DiscountPercent")
    protected BigDecimal discountPercent;
    @XmlElement(name = "DiscountAmount")
    protected CurrencyAmountType discountAmount;
    @XmlElement(name = "NewPrice")
    protected CurrencyAmountType newPrice;
    @XmlElement(name = "Item")
    protected List<ItemAndPriceType> item;
    @XmlElement(name = "StoreID")
    protected List<String> storeID;
    @XmlElement(name = "CancelItems")
    protected List<CancelItemsType> cancelItems;
    @XmlAttribute(name = "ChangeType")
    protected ChangeTypeType changeType;
    @XmlAttribute(name = "ItemPriceCategory")
    protected ItemPriceCategoryType itemPriceCategory;
    @XmlAttribute(name = "ID", required = true)
    protected int id;
    @XmlAttribute(name = "StartDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateTime;
    @XmlAttribute(name = "EndDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateTime;
    @XmlAttribute(name = "Type", required = true)
    protected PricePromotionTypeType type;
    @XmlAttribute(name = "Priority")
    protected Integer priority;
    @XmlAttribute(name = "TemplateType")
    protected String templateType;
    @XmlAttribute(name = "PricingGroupID")
    protected Integer pricingGroupID;
    @XmlAttribute(name = "PromoCompID")
    protected Integer promoCompID;
    @XmlAttribute(name = "PromoCompDetlID")
    protected Integer promoCompDetlID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedNameType }
     *     
     */
    public LocalizedNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedNameType }
     *     
     */
    public void setName(LocalizedNameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedDescriptionType }
     *     
     */
    public LocalizedDescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedDescriptionType }
     *     
     */
    public void setDescription(LocalizedDescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the localizedNameDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedNameDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedNameDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedNameDescriptionType }
     * 
     * 
     */
    public List<LocalizedNameDescriptionType> getLocalizedNameDescription() {
        if (localizedNameDescription == null) {
            localizedNameDescription = new ArrayList<LocalizedNameDescriptionType>();
        }
        return this.localizedNameDescription;
    }

    /**
     * Gets the value of the discountPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountPercent() {
        return discountPercent;
    }

    /**
     * Sets the value of the discountPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountPercent(BigDecimal value) {
        this.discountPercent = value;
    }

    /**
     * Gets the value of the discountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmountType }
     *     
     */
    public CurrencyAmountType getDiscountAmount() {
        return discountAmount;
    }

    /**
     * Sets the value of the discountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmountType }
     *     
     */
    public void setDiscountAmount(CurrencyAmountType value) {
        this.discountAmount = value;
    }

    /**
     * Gets the value of the newPrice property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmountType }
     *     
     */
    public CurrencyAmountType getNewPrice() {
        return newPrice;
    }

    /**
     * Sets the value of the newPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmountType }
     *     
     */
    public void setNewPrice(CurrencyAmountType value) {
        this.newPrice = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemAndPriceType }
     * 
     * 
     */
    public List<ItemAndPriceType> getItem() {
        if (item == null) {
            item = new ArrayList<ItemAndPriceType>();
        }
        return this.item;
    }

    /**
     * Gets the value of the storeID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storeID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoreID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStoreID() {
        if (storeID == null) {
            storeID = new ArrayList<String>();
        }
        return this.storeID;
    }

    /**
     * Gets the value of the cancelItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cancelItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCancelItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CancelItemsType }
     * 
     * 
     */
    public List<CancelItemsType> getCancelItems() {
        if (cancelItems == null) {
            cancelItems = new ArrayList<CancelItemsType>();
        }
        return this.cancelItems;
    }

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeType }
     *     
     */
    public ChangeTypeType getChangeType() {
        if (changeType == null) {
            return ChangeTypeType.ADD;
        } else {
            return changeType;
        }
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeType }
     *     
     */
    public void setChangeType(ChangeTypeType value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the itemPriceCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPriceCategoryType }
     *     
     */
    public ItemPriceCategoryType getItemPriceCategory() {
        if (itemPriceCategory == null) {
            return ItemPriceCategoryType.REGULAR;
        } else {
            return itemPriceCategory;
        }
    }

    /**
     * Sets the value of the itemPriceCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPriceCategoryType }
     *     
     */
    public void setItemPriceCategory(ItemPriceCategoryType value) {
        this.itemPriceCategory = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateTime(XMLGregorianCalendar value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateTime(XMLGregorianCalendar value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PricePromotionTypeType }
     *     
     */
    public PricePromotionTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricePromotionTypeType }
     *     
     */
    public void setType(PricePromotionTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPriority() {
        if (priority == null) {
            return  0;
        } else {
            return priority;
        }
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the templateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateType() {
        if (templateType == null) {
            return "*DEFAULT";
        } else {
            return templateType;
        }
    }

    /**
     * Sets the value of the templateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateType(String value) {
        this.templateType = value;
    }

    /**
     * Gets the value of the pricingGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPricingGroupID() {
        return pricingGroupID;
    }

    /**
     * Sets the value of the pricingGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPricingGroupID(Integer value) {
        this.pricingGroupID = value;
    }

    /**
     * Gets the value of the promoCompID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPromoCompID() {
        return promoCompID;
    }

    /**
     * Sets the value of the promoCompID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPromoCompID(Integer value) {
        this.promoCompID = value;
    }

    /**
     * Gets the value of the promoCompDetlID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPromoCompDetlID() {
        return promoCompDetlID;
    }

    /**
     * Sets the value of the promoCompDetlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPromoCompDetlID(Integer value) {
        this.promoCompDetlID = value;
    }

}
