//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 11:57:08 AM IST 
//


package rispl.jaxb.item.pricing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PricingRule_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingRule_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Name" type="{}LocalizedName_type" minOccurs="0"/>
 *           &lt;element name="LocalizedName" type="{}LocalizedNameDescription_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="SourceThreshold" type="{}CurrencyAmount_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SourceLimit" type="{}CurrencyAmount_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TargetThreshold" type="{}CurrencyAmount_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TargetLimit" type="{}CurrencyAmount_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StoreID" type="{}RetailStoreId_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}PromotionComponentAttributes"/>
 *       &lt;attribute name="ChangeType" type="{}ChangeType_type" default="ADD" />
 *       &lt;attribute name="SourceItemPriceCategory" type="{}ItemPriceCategory_type" default="Both" />
 *       &lt;attribute name="TargetItemPriceCategory" type="{}ItemPriceCategory_type" default="Both" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="StartDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Type" use="required" type="{}RuleType_type" />
 *       &lt;attribute name="NbrTimesPerTrans" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *       &lt;attribute name="AccountingMethod" type="{}AccountingMethodType_type" default="Discount" />
 *       &lt;attribute name="AllowSourceToRepeat" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="DealDistribution" type="{}DealDistributionType_type" default="Target" />
 *       &lt;attribute name="Scope" type="{}ScopeType_type" default="Item" />
 *       &lt;attribute name="PricingGroupID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingRule_type", propOrder = {
    "name",
    "localizedName",
    "sourceThreshold",
    "sourceLimit",
    "targetThreshold",
    "targetLimit",
    "storeID"
})
public class PricingRuleType {

    @XmlElement(name = "Name")
    protected LocalizedNameType name;
    @XmlElement(name = "LocalizedName")
    protected List<LocalizedNameDescriptionType> localizedName;
    @XmlElement(name = "SourceThreshold")
    protected List<CurrencyAmountType> sourceThreshold;
    @XmlElement(name = "SourceLimit")
    protected List<CurrencyAmountType> sourceLimit;
    @XmlElement(name = "TargetThreshold")
    protected List<CurrencyAmountType> targetThreshold;
    @XmlElement(name = "TargetLimit")
    protected List<CurrencyAmountType> targetLimit;
    @XmlElement(name = "StoreID")
    protected List<String> storeID;
    @XmlAttribute(name = "ChangeType")
    protected ChangeTypeType changeType;
    @XmlAttribute(name = "SourceItemPriceCategory")
    protected ItemPriceCategoryType sourceItemPriceCategory;
    @XmlAttribute(name = "TargetItemPriceCategory")
    protected ItemPriceCategoryType targetItemPriceCategory;
    @XmlAttribute(name = "ID", required = true)
    protected int id;
    @XmlAttribute(name = "StartDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateTime;
    @XmlAttribute(name = "EndDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateTime;
    @XmlAttribute(name = "Type", required = true)
    protected RuleTypeType type;
    @XmlAttribute(name = "NbrTimesPerTrans")
    protected Integer nbrTimesPerTrans;
    @XmlAttribute(name = "AccountingMethod")
    protected AccountingMethodTypeType accountingMethod;
    @XmlAttribute(name = "AllowSourceToRepeat")
    protected Boolean allowSourceToRepeat;
    @XmlAttribute(name = "DealDistribution")
    protected DealDistributionTypeType dealDistribution;
    @XmlAttribute(name = "Scope")
    protected ScopeTypeType scope;
    @XmlAttribute(name = "PricingGroupID")
    protected Integer pricingGroupID;
    @XmlAttribute(name = "PromoCompID")
    protected Integer promoCompID;
    @XmlAttribute(name = "PromoCompDetlID")
    protected Integer promoCompDetlID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedNameType }
     *     
     */
    public LocalizedNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedNameType }
     *     
     */
    public void setName(LocalizedNameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the localizedName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedNameDescriptionType }
     * 
     * 
     */
    public List<LocalizedNameDescriptionType> getLocalizedName() {
        if (localizedName == null) {
            localizedName = new ArrayList<LocalizedNameDescriptionType>();
        }
        return this.localizedName;
    }

    /**
     * Gets the value of the sourceThreshold property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceThreshold property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceThreshold().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyAmountType }
     * 
     * 
     */
    public List<CurrencyAmountType> getSourceThreshold() {
        if (sourceThreshold == null) {
            sourceThreshold = new ArrayList<CurrencyAmountType>();
        }
        return this.sourceThreshold;
    }

    /**
     * Gets the value of the sourceLimit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceLimit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceLimit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyAmountType }
     * 
     * 
     */
    public List<CurrencyAmountType> getSourceLimit() {
        if (sourceLimit == null) {
            sourceLimit = new ArrayList<CurrencyAmountType>();
        }
        return this.sourceLimit;
    }

    /**
     * Gets the value of the targetThreshold property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetThreshold property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetThreshold().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyAmountType }
     * 
     * 
     */
    public List<CurrencyAmountType> getTargetThreshold() {
        if (targetThreshold == null) {
            targetThreshold = new ArrayList<CurrencyAmountType>();
        }
        return this.targetThreshold;
    }

    /**
     * Gets the value of the targetLimit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetLimit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetLimit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyAmountType }
     * 
     * 
     */
    public List<CurrencyAmountType> getTargetLimit() {
        if (targetLimit == null) {
            targetLimit = new ArrayList<CurrencyAmountType>();
        }
        return this.targetLimit;
    }

    /**
     * Gets the value of the storeID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storeID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoreID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStoreID() {
        if (storeID == null) {
            storeID = new ArrayList<String>();
        }
        return this.storeID;
    }

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeType }
     *     
     */
    public ChangeTypeType getChangeType() {
        if (changeType == null) {
            return ChangeTypeType.ADD;
        } else {
            return changeType;
        }
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeType }
     *     
     */
    public void setChangeType(ChangeTypeType value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the sourceItemPriceCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPriceCategoryType }
     *     
     */
    public ItemPriceCategoryType getSourceItemPriceCategory() {
        if (sourceItemPriceCategory == null) {
            return ItemPriceCategoryType.BOTH;
        } else {
            return sourceItemPriceCategory;
        }
    }

    /**
     * Sets the value of the sourceItemPriceCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPriceCategoryType }
     *     
     */
    public void setSourceItemPriceCategory(ItemPriceCategoryType value) {
        this.sourceItemPriceCategory = value;
    }

    /**
     * Gets the value of the targetItemPriceCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPriceCategoryType }
     *     
     */
    public ItemPriceCategoryType getTargetItemPriceCategory() {
        if (targetItemPriceCategory == null) {
            return ItemPriceCategoryType.BOTH;
        } else {
            return targetItemPriceCategory;
        }
    }

    /**
     * Sets the value of the targetItemPriceCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPriceCategoryType }
     *     
     */
    public void setTargetItemPriceCategory(ItemPriceCategoryType value) {
        this.targetItemPriceCategory = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateTime(XMLGregorianCalendar value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateTime(XMLGregorianCalendar value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RuleTypeType }
     *     
     */
    public RuleTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleTypeType }
     *     
     */
    public void setType(RuleTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the nbrTimesPerTrans property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNbrTimesPerTrans() {
        if (nbrTimesPerTrans == null) {
            return -1;
        } else {
            return nbrTimesPerTrans;
        }
    }

    /**
     * Sets the value of the nbrTimesPerTrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNbrTimesPerTrans(Integer value) {
        this.nbrTimesPerTrans = value;
    }

    /**
     * Gets the value of the accountingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingMethodTypeType }
     *     
     */
    public AccountingMethodTypeType getAccountingMethod() {
        if (accountingMethod == null) {
            return AccountingMethodTypeType.DISCOUNT;
        } else {
            return accountingMethod;
        }
    }

    /**
     * Sets the value of the accountingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingMethodTypeType }
     *     
     */
    public void setAccountingMethod(AccountingMethodTypeType value) {
        this.accountingMethod = value;
    }

    /**
     * Gets the value of the allowSourceToRepeat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowSourceToRepeat() {
        if (allowSourceToRepeat == null) {
            return true;
        } else {
            return allowSourceToRepeat;
        }
    }

    /**
     * Sets the value of the allowSourceToRepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSourceToRepeat(Boolean value) {
        this.allowSourceToRepeat = value;
    }

    /**
     * Gets the value of the dealDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link DealDistributionTypeType }
     *     
     */
    public DealDistributionTypeType getDealDistribution() {
        if (dealDistribution == null) {
            return DealDistributionTypeType.TARGET;
        } else {
            return dealDistribution;
        }
    }

    /**
     * Sets the value of the dealDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealDistributionTypeType }
     *     
     */
    public void setDealDistribution(DealDistributionTypeType value) {
        this.dealDistribution = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link ScopeTypeType }
     *     
     */
    public ScopeTypeType getScope() {
        if (scope == null) {
            return ScopeTypeType.ITEM;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopeTypeType }
     *     
     */
    public void setScope(ScopeTypeType value) {
        this.scope = value;
    }

    /**
     * Gets the value of the pricingGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPricingGroupID() {
        return pricingGroupID;
    }

    /**
     * Sets the value of the pricingGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPricingGroupID(Integer value) {
        this.pricingGroupID = value;
    }

    /**
     * Gets the value of the promoCompID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPromoCompID() {
        return promoCompID;
    }

    /**
     * Sets the value of the promoCompID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPromoCompID(Integer value) {
        this.promoCompID = value;
    }

    /**
     * Gets the value of the promoCompDetlID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPromoCompDetlID() {
        return promoCompDetlID;
    }

    /**
     * Sets the value of the promoCompDetlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPromoCompDetlID(Integer value) {
        this.promoCompDetlID = value;
    }

}
