//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 11:57:08 AM IST 
//


package rispl.jaxb.item.pricing;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleType_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RuleType_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BuyNofXgetYatZ%off"/>
 *     &lt;enumeration value="BuyNofXgetYatZ$off"/>
 *     &lt;enumeration value="BuyNofXgetYatZ$"/>
 *     &lt;enumeration value="BuyNofXgetHighestPricedXatZ%off"/>
 *     &lt;enumeration value="BuyNofXgetLowestPricedXatZ%off"/>
 *     &lt;enumeration value="Buy$NorMoreOfXgetYatZ$off"/>
 *     &lt;enumeration value="Buy$NorMoreOfXgetYatZ%off"/>
 *     &lt;enumeration value="Buy$NorMoreOfXgetYatZ$"/>
 *     &lt;enumeration value="BuyNofXforZ$"/>
 *     &lt;enumeration value="BuyNofXforZ%off"/>
 *     &lt;enumeration value="BuyNofXforZ$off"/>
 *     &lt;enumeration value="BuyNorMoreOfXforZ%off"/>
 *     &lt;enumeration value="BuyNorMoreOfXforZ$Each"/>
 *     &lt;enumeration value="Buy$NofXforZ$off"/>
 *     &lt;enumeration value="Buy$NofXforZ%off"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RuleType_type")
@XmlEnum
public enum RuleTypeType {

    @XmlEnumValue("BuyNofXgetYatZ%off")
    BUY_NOF_XGET_YAT_Z_OFF("BuyNofXgetYatZ%off"),
    @XmlEnumValue("BuyNofXgetYatZ$off")
    BUY_NOF_XGET_YAT_Z_$_OFF("BuyNofXgetYatZ$off"),
    @XmlEnumValue("BuyNofXgetYatZ$")
    BUY_NOF_XGET_YAT_Z_$("BuyNofXgetYatZ$"),
    @XmlEnumValue("BuyNofXgetHighestPricedXatZ%off")
    BUY_NOF_XGET_HIGHEST_PRICED_XAT_Z_OFF("BuyNofXgetHighestPricedXatZ%off"),
    @XmlEnumValue("BuyNofXgetLowestPricedXatZ%off")
    BUY_NOF_XGET_LOWEST_PRICED_XAT_Z_OFF("BuyNofXgetLowestPricedXatZ%off"),
    @XmlEnumValue("Buy$NorMoreOfXgetYatZ$off")
    BUY_$_NOR_MORE_OF_XGET_YAT_Z_$_OFF("Buy$NorMoreOfXgetYatZ$off"),
    @XmlEnumValue("Buy$NorMoreOfXgetYatZ%off")
    BUY_$_NOR_MORE_OF_XGET_YAT_Z_OFF("Buy$NorMoreOfXgetYatZ%off"),
    @XmlEnumValue("Buy$NorMoreOfXgetYatZ$")
    BUY_$_NOR_MORE_OF_XGET_YAT_Z_$("Buy$NorMoreOfXgetYatZ$"),
    @XmlEnumValue("BuyNofXforZ$")
    BUY_NOF_XFOR_Z_$("BuyNofXforZ$"),
    @XmlEnumValue("BuyNofXforZ%off")
    BUY_NOF_XFOR_Z_OFF("BuyNofXforZ%off"),
    @XmlEnumValue("BuyNofXforZ$off")
    BUY_NOF_XFOR_Z_$_OFF("BuyNofXforZ$off"),
    @XmlEnumValue("BuyNorMoreOfXforZ%off")
    BUY_NOR_MORE_OF_XFOR_Z_OFF("BuyNorMoreOfXforZ%off"),
    @XmlEnumValue("BuyNorMoreOfXforZ$Each")
    BUY_NOR_MORE_OF_XFOR_Z_$_EACH("BuyNorMoreOfXforZ$Each"),
    @XmlEnumValue("Buy$NofXforZ$off")
    BUY_$_NOF_XFOR_Z_$_OFF("Buy$NofXforZ$off"),
    @XmlEnumValue("Buy$NofXforZ%off")
    BUY_$_NOF_XFOR_Z_OFF("Buy$NofXforZ%off");
    private final String value;

    RuleTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RuleTypeType fromValue(String v) {
        for (RuleTypeType c: RuleTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
