//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 02:46:01 PM IST 
//


package rispl.jaxb.storehierarchy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreloadData_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreloadData_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StoreRegion" type="{}StoreRegion_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StoreDistrict" type="{}StoreDistrict_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RetailStore" type="{}RetailStore_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreloadData_type", propOrder = {
    "storeRegion",
    "storeDistrict",
    "retailStore"
})
public class PreloadDataType {

    @XmlElement(name = "StoreRegion")
    protected List<StoreRegionType> storeRegion;
    @XmlElement(name = "StoreDistrict")
    protected List<StoreDistrictType> storeDistrict;
    @XmlElement(name = "RetailStore")
    protected List<RetailStoreType> retailStore;

    /**
     * Gets the value of the storeRegion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storeRegion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoreRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StoreRegionType }
     * 
     * 
     */
    public List<StoreRegionType> getStoreRegion() {
        if (storeRegion == null) {
            storeRegion = new ArrayList<StoreRegionType>();
        }
        return this.storeRegion;
    }

    /**
     * Gets the value of the storeDistrict property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storeDistrict property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoreDistrict().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StoreDistrictType }
     * 
     * 
     */
    public List<StoreDistrictType> getStoreDistrict() {
        if (storeDistrict == null) {
            storeDistrict = new ArrayList<StoreDistrictType>();
        }
        return this.storeDistrict;
    }

    /**
     * Gets the value of the retailStore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retailStore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetailStore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetailStoreType }
     * 
     * 
     */
    public List<RetailStoreType> getRetailStore() {
        if (retailStore == null) {
            retailStore = new ArrayList<RetailStoreType>();
        }
        return this.retailStore;
    }

}
