package rispl.dkart.services.entities.transaction;

import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2018-01-09T13:30:35.304+0530")
@StaticMetamodel(OrderTranLineItem.class)
public class OrderTranLineItem_ {
	public static volatile SingularAttribute<OrderTranLineItem, OrderTranLineItemPK> id;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> aiLnItmOrg;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> aiLnItmRltd;
	public static volatile SingularAttribute<OrderTranLineItem, String> dcDyBsnOrg;
	public static volatile SingularAttribute<OrderTranLineItem, String> deItmLcl;
	public static volatile SingularAttribute<OrderTranLineItem, String> deItmShrtRcpt;
	public static volatile SingularAttribute<OrderTranLineItem, String> dkDptId;
	public static volatile SingularAttribute<OrderTranLineItem, String> dkItmId;
	public static volatile SingularAttribute<OrderTranLineItem, String> edSz;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> extnDscLnItm;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> extnLnItmRtn;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> feRstk;
	public static volatile SingularAttribute<OrderTranLineItem, String> flClrnc;
	public static volatile SingularAttribute<OrderTranLineItem, String> flDscEmAlw;
	public static volatile SingularAttribute<OrderTranLineItem, String> flFeRstk;
	public static volatile SingularAttribute<OrderTranLineItem, String> flItmDsc;
	public static volatile SingularAttribute<OrderTranLineItem, String> flItmDscDmg;
	public static volatile SingularAttribute<OrderTranLineItem, String> flItmPrcAdj;
	public static volatile SingularAttribute<OrderTranLineItem, String> flItmSzReq;
	public static volatile SingularAttribute<OrderTranLineItem, String> flMdfrPrc;
	public static volatile SingularAttribute<OrderTranLineItem, String> flRfdSv;
	public static volatile SingularAttribute<OrderTranLineItem, String> flRltdItmRm;
	public static volatile SingularAttribute<OrderTranLineItem, String> flRltdItmRtn;
	public static volatile SingularAttribute<OrderTranLineItem, String> flRtnMr;
	public static volatile SingularAttribute<OrderTranLineItem, String> flRtnPrh;
	public static volatile SingularAttribute<OrderTranLineItem, String> flRtrvdTrn;
	public static volatile SingularAttribute<OrderTranLineItem, String> flShpChg;
	public static volatile SingularAttribute<OrderTranLineItem, String> flSlsAsscMdf;
	public static volatile SingularAttribute<OrderTranLineItem, String> flTx;
	public static volatile SingularAttribute<OrderTranLineItem, String> flVdLnItm;
	public static volatile SingularAttribute<OrderTranLineItem, String> flVldSrzItm;
	public static volatile SingularAttribute<OrderTranLineItem, String> flVldSrzItmExt;
	public static volatile SingularAttribute<OrderTranLineItem, String> idCln;
	public static volatile SingularAttribute<OrderTranLineItem, String> idItmMfUpc;
	public static volatile SingularAttribute<OrderTranLineItem, String> idMrhrcGp;
	public static volatile SingularAttribute<OrderTranLineItem, String> idNmbSrz;
	public static volatile SingularAttribute<OrderTranLineItem, String> idNonRtvdOrgRcpt;
	public static volatile SingularAttribute<OrderTranLineItem, String> idStrRtOrg;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> idnSlsAgRst;
	public static volatile SingularAttribute<OrderTranLineItem, String> itemId;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> itmPrnPrc;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> itmTy;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> lineQnt;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> lineQntRtn;
	public static volatile SingularAttribute<OrderTranLineItem, String> luEntrRtPrc;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> luKtHdrRfnId;
	public static volatile SingularAttribute<OrderTranLineItem, String> luKtSt;
	public static volatile SingularAttribute<OrderTranLineItem, String> luMthIdEnr;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> luPrcAdjRfnId;
	public static volatile SingularAttribute<OrderTranLineItem, String> luPrcRtDrvn;
	public static volatile SingularAttribute<OrderTranLineItem, String> mrLvHrc;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> orId;
	public static volatile SingularAttribute<OrderTranLineItem, String> ordIdTrnOrg;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> ordLnItmSts;
	public static volatile SingularAttribute<OrderTranLineItem, String> rcItmCndRtnMr;
	public static volatile SingularAttribute<OrderTranLineItem, String> rcRfdSv;
	public static volatile SingularAttribute<OrderTranLineItem, String> rcRtnMr;
	public static volatile SingularAttribute<OrderTranLineItem, String> registryId;
	public static volatile SingularAttribute<OrderTranLineItem, String> exciseTax;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> taxIncLnItmRtn;
	public static volatile SingularAttribute<OrderTranLineItem, Date> tsCrtRcrd;
	public static volatile SingularAttribute<OrderTranLineItem, Date> tsMdfRcrd;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> txGpId;
	public static volatile SingularAttribute<OrderTranLineItem, String> uomSls;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> vatLnItmRtn;
	public static volatile ListAttribute<OrderTranLineItem, OrderTranDiscountItem> ordTranDscItms;
	public static volatile SingularAttribute<OrderTranLineItem, OrderTranHeader> ordTranHeader;
	public static volatile SingularAttribute<OrderTranLineItem, String> priceOvrrRsnCode;
	public static volatile SingularAttribute<OrderTranLineItem, BigDecimal> overRidePrice;
	public static volatile SingularAttribute<OrderTranLineItem, String> priceOverRideFlag;
	public static volatile SingularAttribute<OrderTranLineItem, String> returnQtyFlag;
	public static volatile SingularAttribute<OrderTranLineItem, String> empId;
	public static volatile SingularAttribute<OrderTranLineItem, String> dispostionCode;
}
