
package com.rsi.dk.wms.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import wms.dk.rsi.customerdetails.CustomerOrderCancelDetails;
import wms.dk.rsi.customerdetails.CustomerOrderCancelStatus;
import wms.dk.rsi.customerdetails.CustomerOrderCreationDetails;
import wms.dk.rsi.customerdetails.CustomerOrderCreationStatus;
import wms.dk.rsi.customerdetails.CustomerOrderReturnDetails;
import wms.dk.rsi.customerdetails.CustomerOrderReturnStatus;
import wms.dk.rsi.customerdetails.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerOrder", targetNamespace = "http://customerDetails.rsi.dk.wms")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerOrder {


    /**
     * 
     * @param createCustomerOrderList
     * @return
     *     returns java.util.List<wms.dk.rsi.customerdetails.CustomerOrderCreationStatus>
     * @throws CustomerOrderException
     */
    @WebMethod
    @WebResult(name = "createOrderStatus", targetNamespace = "")
    @RequestWrapper(localName = "createCustomerOrder", targetNamespace = "http://customerDetails.rsi.dk.wms", className = "wms.dk.rsi.customerdetails.CreateCustomerOrder")
    @ResponseWrapper(localName = "createCustomerOrderResponse", targetNamespace = "http://customerDetails.rsi.dk.wms", className = "wms.dk.rsi.customerdetails.CreateCustomerOrderResponse")
    @Action(input = "http://customerDetails.rsi.dk.wms/CustomerOrder/createCustomerOrderRequest", output = "http://customerDetails.rsi.dk.wms/CustomerOrder/createCustomerOrderResponse", fault = {
        @FaultAction(className = CustomerOrderException.class, value = "http://customerDetails.rsi.dk.wms/CustomerOrder/createCustomerOrder/Fault/CustomerOrderException")
    })
    public List<CustomerOrderCreationStatus> createCustomerOrder(
        @WebParam(name = "createCustomerOrderList", targetNamespace = "")
        List<CustomerOrderCreationDetails> createCustomerOrderList)
        throws CustomerOrderException
    ;

    /**
     * 
     * @param cancelCustomerOrderList
     * @return
     *     returns java.util.List<wms.dk.rsi.customerdetails.CustomerOrderCancelStatus>
     * @throws CustomerOrderException
     */
    @WebMethod
    @WebResult(name = "cancelOrderStatus", targetNamespace = "")
    @RequestWrapper(localName = "cancelCustomerOrder", targetNamespace = "http://customerDetails.rsi.dk.wms", className = "wms.dk.rsi.customerdetails.CancelCustomerOrder")
    @ResponseWrapper(localName = "cancelCustomerOrderResponse", targetNamespace = "http://customerDetails.rsi.dk.wms", className = "wms.dk.rsi.customerdetails.CancelCustomerOrderResponse")
    @Action(input = "http://customerDetails.rsi.dk.wms/CustomerOrder/cancelCustomerOrderRequest", output = "http://customerDetails.rsi.dk.wms/CustomerOrder/cancelCustomerOrderResponse", fault = {
        @FaultAction(className = CustomerOrderException.class, value = "http://customerDetails.rsi.dk.wms/CustomerOrder/cancelCustomerOrder/Fault/CustomerOrderException")
    })
    public List<CustomerOrderCancelStatus> cancelCustomerOrder(
        @WebParam(name = "cancelCustomerOrderList", targetNamespace = "")
        List<CustomerOrderCancelDetails> cancelCustomerOrderList)
        throws CustomerOrderException
    ;

    /**
     * 
     * @param returnCustomerOrderList
     * @return
     *     returns java.util.List<wms.dk.rsi.customerdetails.CustomerOrderReturnStatus>
     * @throws CustomerOrderException
     */
    @WebMethod
    @WebResult(name = "returnOrderStatus", targetNamespace = "")
    @RequestWrapper(localName = "returnCustomerOrder", targetNamespace = "http://customerDetails.rsi.dk.wms", className = "wms.dk.rsi.customerdetails.ReturnCustomerOrder")
    @ResponseWrapper(localName = "returnCustomerOrderResponse", targetNamespace = "http://customerDetails.rsi.dk.wms", className = "wms.dk.rsi.customerdetails.ReturnCustomerOrderResponse")
    @Action(input = "http://customerDetails.rsi.dk.wms/CustomerOrder/returnCustomerOrderRequest", output = "http://customerDetails.rsi.dk.wms/CustomerOrder/returnCustomerOrderResponse", fault = {
        @FaultAction(className = CustomerOrderException.class, value = "http://customerDetails.rsi.dk.wms/CustomerOrder/returnCustomerOrder/Fault/CustomerOrderException")
    })
    public List<CustomerOrderReturnStatus> returnCustomerOrder(
        @WebParam(name = "returnCustomerOrderList", targetNamespace = "")
        List<CustomerOrderReturnDetails> returnCustomerOrderList)
        throws CustomerOrderException
    ;

}
