
package com.rsi.dk.wms.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerOrderService", targetNamespace = "http://service.wms.dk.rsi.com/", wsdlLocation = "http://192.168.145.33:7004/CustomerOrderServiceQatar/CustomerOrderService?WSDL")
public class CustomerOrderService
    extends Service
{

    private final static URL CUSTOMERORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERORDERSERVICE_EXCEPTION;
    private final static QName CUSTOMERORDERSERVICE_QNAME = new QName("http://service.wms.dk.rsi.com/", "CustomerOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.145.33:7004/CustomerOrderServiceQatar/CustomerOrderService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERORDERSERVICE_WSDL_LOCATION = url;
        CUSTOMERORDERSERVICE_EXCEPTION = e;
    }

    public CustomerOrderService() {
        super(__getWsdlLocation(), CUSTOMERORDERSERVICE_QNAME);
    }

    public CustomerOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERORDERSERVICE_QNAME, features);
    }

    public CustomerOrderService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERORDERSERVICE_QNAME);
    }

    public CustomerOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERORDERSERVICE_QNAME, features);
    }

    public CustomerOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerOrder
     */
    @WebEndpoint(name = "CustomerOrderPort")
    public CustomerOrder getCustomerOrderPort() {
        return super.getPort(new QName("http://service.wms.dk.rsi.com/", "CustomerOrderPort"), CustomerOrder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerOrder
     */
    @WebEndpoint(name = "CustomerOrderPort")
    public CustomerOrder getCustomerOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wms.dk.rsi.com/", "CustomerOrderPort"), CustomerOrder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERORDERSERVICE_EXCEPTION!= null) {
            throw CUSTOMERORDERSERVICE_EXCEPTION;
        }
        return CUSTOMERORDERSERVICE_WSDL_LOCATION;
    }

}
