//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:22:41 PM IST 
//


package rispl.jaxb.tax;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GEOCode_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GEOCode_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeoCodeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxJurisdictionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GEOCode_type", propOrder = {
    "geoCodeID",
    "taxJurisdictionName"
})
public class GEOCodeType {

    @XmlElement(name = "GeoCodeID", required = true)
    protected String geoCodeID;
    @XmlElement(name = "TaxJurisdictionName", required = true)
    protected String taxJurisdictionName;

    /**
     * Gets the value of the geoCodeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoCodeID() {
        return geoCodeID;
    }

    /**
     * Sets the value of the geoCodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoCodeID(String value) {
        this.geoCodeID = value;
    }

    /**
     * Gets the value of the taxJurisdictionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxJurisdictionName() {
        return taxJurisdictionName;
    }

    /**
     * Sets the value of the taxJurisdictionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxJurisdictionName(String value) {
        this.taxJurisdictionName = value;
    }

}
