//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:22:41 PM IST 
//


package rispl.jaxb.tax;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rispl.jaxb.tax package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rispl.jaxb.tax
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link TaxRateRuleType }
     * 
     */
    public TaxRateRuleType createTaxRateRuleType() {
        return new TaxRateRuleType();
    }

    /**
     * Create an instance of {@link TaxGroupRuleType }
     * 
     */
    public TaxGroupRuleType createTaxGroupRuleType() {
        return new TaxGroupRuleType();
    }

    /**
     * Create an instance of {@link NameDescriptionType }
     * 
     */
    public NameDescriptionType createNameDescriptionType() {
        return new NameDescriptionType();
    }

    /**
     * Create an instance of {@link GEOCodeType }
     * 
     */
    public GEOCodeType createGEOCodeType() {
        return new GEOCodeType();
    }

    /**
     * Create an instance of {@link TaxImport }
     * 
     */
    public TaxImport createTaxImport() {
        return new TaxImport();
    }

    /**
     * Create an instance of {@link LocalizedDescriptionType }
     * 
     */
    public LocalizedDescriptionType createLocalizedDescriptionType() {
        return new LocalizedDescriptionType();
    }

    /**
     * Create an instance of {@link LocalizedMessageDescriptionType }
     * 
     */
    public LocalizedMessageDescriptionType createLocalizedMessageDescriptionType() {
        return new LocalizedMessageDescriptionType();
    }

    /**
     * Create an instance of {@link GEOTaxJurisdictionType }
     * 
     */
    public GEOTaxJurisdictionType createGEOTaxJurisdictionType() {
        return new GEOTaxJurisdictionType();
    }

    /**
     * Create an instance of {@link TaxAuthorityType }
     * 
     */
    public TaxAuthorityType createTaxAuthorityType() {
        return new TaxAuthorityType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link LocalizedNameDescriptionType }
     * 
     */
    public LocalizedNameDescriptionType createLocalizedNameDescriptionType() {
        return new LocalizedNameDescriptionType();
    }

    /**
     * Create an instance of {@link TaxableGroupType }
     * 
     */
    public TaxableGroupType createTaxableGroupType() {
        return new TaxableGroupType();
    }

    /**
     * Create an instance of {@link LocalizedItemSizeDescriptionType }
     * 
     */
    public LocalizedItemSizeDescriptionType createLocalizedItemSizeDescriptionType() {
        return new LocalizedItemSizeDescriptionType();
    }

}
