//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:22:41 PM IST 
//


package rispl.jaxb.tax;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxableGroup_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxableGroup_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxGroupID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TaxGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxGroupDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceiptPrintCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="LocalizedTaxGroupNameDescription" type="{}LocalizedNameDescription_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxableGroup_type", propOrder = {
    "taxGroupID",
    "taxGroupName",
    "taxGroupDescription",
    "receiptPrintCode",
    "localizedTaxGroupNameDescription"
})
public class TaxableGroupType {

    @XmlElement(name = "TaxGroupID", required = true)
    protected BigInteger taxGroupID;
    @XmlElement(name = "TaxGroupName", required = true)
    protected String taxGroupName;
    @XmlElement(name = "TaxGroupDescription", required = true)
    protected String taxGroupDescription;
    @XmlElement(name = "ReceiptPrintCode")
    protected BigInteger receiptPrintCode;
    @XmlElement(name = "LocalizedTaxGroupNameDescription")
    protected List<LocalizedNameDescriptionType> localizedTaxGroupNameDescription;

    /**
     * Gets the value of the taxGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTaxGroupID() {
        return taxGroupID;
    }

    /**
     * Sets the value of the taxGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTaxGroupID(BigInteger value) {
        this.taxGroupID = value;
    }

    /**
     * Gets the value of the taxGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxGroupName() {
        return taxGroupName;
    }

    /**
     * Sets the value of the taxGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxGroupName(String value) {
        this.taxGroupName = value;
    }

    /**
     * Gets the value of the taxGroupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxGroupDescription() {
        return taxGroupDescription;
    }

    /**
     * Sets the value of the taxGroupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxGroupDescription(String value) {
        this.taxGroupDescription = value;
    }

    /**
     * Gets the value of the receiptPrintCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReceiptPrintCode() {
        return receiptPrintCode;
    }

    /**
     * Sets the value of the receiptPrintCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReceiptPrintCode(BigInteger value) {
        this.receiptPrintCode = value;
    }

    /**
     * Gets the value of the localizedTaxGroupNameDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedTaxGroupNameDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedTaxGroupNameDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedNameDescriptionType }
     * 
     * 
     */
    public List<LocalizedNameDescriptionType> getLocalizedTaxGroupNameDescription() {
        if (localizedTaxGroupNameDescription == null) {
            localizedTaxGroupNameDescription = new ArrayList<LocalizedNameDescriptionType>();
        }
        return this.localizedTaxGroupNameDescription;
    }

}
