//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:22:41 PM IST 
//


package rispl.jaxb.tax;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TaxGroupRule_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxGroupRule_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxAuthorityID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TaxGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxTypeID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TaxTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxHolidayFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="TaxRuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxRuleDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompoundRateSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TaxOnGrossAmountFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CalculationMethodCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="LineItem"/>
 *               &lt;enumeration value="Transaction"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxRateRuleUsageCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="PercentageOrAmount"/>
 *               &lt;enumeration value="DeriveFromTaxTable"/>
 *               &lt;enumeration value="UseThresholdAmount"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InclusiveTaxFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="TaxRateRule" type="{}TaxRateRule_type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxGroupRule_type", propOrder = {
    "taxAuthorityID",
    "taxGroupID",
    "taxTypeID",
    "taxTypeName",
    "taxHolidayFlag",
    "taxRuleName",
    "taxRuleDescription",
    "compoundRateSequenceNumber",
    "taxOnGrossAmountFlag",
    "calculationMethodCode",
    "taxRateRuleUsageCode",
    "inclusiveTaxFlag",
    "taxRateRule"
})
public class TaxGroupRuleType {

    @XmlElement(name = "TaxAuthorityID", required = true)
    protected BigInteger taxAuthorityID;
    @XmlElement(name = "TaxGroupID", required = true)
    protected String taxGroupID;
    @XmlElement(name = "TaxTypeID", required = true)
    protected BigInteger taxTypeID;
    @XmlElement(name = "TaxTypeName")
    protected String taxTypeName;
    @XmlElement(name = "TaxHolidayFlag")
    protected boolean taxHolidayFlag;
    @XmlElement(name = "TaxRuleName", required = true)
    protected String taxRuleName;
    @XmlElement(name = "TaxRuleDescription", required = true)
    protected String taxRuleDescription;
    @XmlElement(name = "CompoundRateSequenceNumber")
    protected BigInteger compoundRateSequenceNumber;
    @XmlElement(name = "TaxOnGrossAmountFlag")
    protected Boolean taxOnGrossAmountFlag;
    @XmlElement(name = "CalculationMethodCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String calculationMethodCode;
    @XmlElement(name = "TaxRateRuleUsageCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String taxRateRuleUsageCode;
    @XmlElement(name = "InclusiveTaxFlag")
    protected boolean inclusiveTaxFlag;
    @XmlElement(name = "TaxRateRule", required = true)
    protected List<TaxRateRuleType> taxRateRule;

    /**
     * Gets the value of the taxAuthorityID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTaxAuthorityID() {
        return taxAuthorityID;
    }

    /**
     * Sets the value of the taxAuthorityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTaxAuthorityID(BigInteger value) {
        this.taxAuthorityID = value;
    }

    /**
     * Gets the value of the taxGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxGroupID() {
        return taxGroupID;
    }

    /**
     * Sets the value of the taxGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxGroupID(String value) {
        this.taxGroupID = value;
    }

    /**
     * Gets the value of the taxTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTaxTypeID() {
        return taxTypeID;
    }

    /**
     * Sets the value of the taxTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTaxTypeID(BigInteger value) {
        this.taxTypeID = value;
    }

    /**
     * Gets the value of the taxTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxTypeName() {
        return taxTypeName;
    }

    /**
     * Sets the value of the taxTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxTypeName(String value) {
        this.taxTypeName = value;
    }

    /**
     * Gets the value of the taxHolidayFlag property.
     * 
     */
    public boolean isTaxHolidayFlag() {
        return taxHolidayFlag;
    }

    /**
     * Sets the value of the taxHolidayFlag property.
     * 
     */
    public void setTaxHolidayFlag(boolean value) {
        this.taxHolidayFlag = value;
    }

    /**
     * Gets the value of the taxRuleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRuleName() {
        return taxRuleName;
    }

    /**
     * Sets the value of the taxRuleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRuleName(String value) {
        this.taxRuleName = value;
    }

    /**
     * Gets the value of the taxRuleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRuleDescription() {
        return taxRuleDescription;
    }

    /**
     * Sets the value of the taxRuleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRuleDescription(String value) {
        this.taxRuleDescription = value;
    }

    /**
     * Gets the value of the compoundRateSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompoundRateSequenceNumber() {
        return compoundRateSequenceNumber;
    }

    /**
     * Sets the value of the compoundRateSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompoundRateSequenceNumber(BigInteger value) {
        this.compoundRateSequenceNumber = value;
    }

    /**
     * Gets the value of the taxOnGrossAmountFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxOnGrossAmountFlag() {
        return taxOnGrossAmountFlag;
    }

    /**
     * Sets the value of the taxOnGrossAmountFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxOnGrossAmountFlag(Boolean value) {
        this.taxOnGrossAmountFlag = value;
    }

    /**
     * Gets the value of the calculationMethodCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculationMethodCode() {
        return calculationMethodCode;
    }

    /**
     * Sets the value of the calculationMethodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculationMethodCode(String value) {
        this.calculationMethodCode = value;
    }

    /**
     * Gets the value of the taxRateRuleUsageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRateRuleUsageCode() {
        return taxRateRuleUsageCode;
    }

    /**
     * Sets the value of the taxRateRuleUsageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRateRuleUsageCode(String value) {
        this.taxRateRuleUsageCode = value;
    }

    /**
     * Gets the value of the inclusiveTaxFlag property.
     * 
     */
    public boolean isInclusiveTaxFlag() {
        return inclusiveTaxFlag;
    }

    /**
     * Sets the value of the inclusiveTaxFlag property.
     * 
     */
    public void setInclusiveTaxFlag(boolean value) {
        this.inclusiveTaxFlag = value;
    }

    /**
     * Gets the value of the taxRateRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxRateRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxRateRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxRateRuleType }
     * 
     * 
     */
    public List<TaxRateRuleType> getTaxRateRule() {
        if (taxRateRule == null) {
            taxRateRule = new ArrayList<TaxRateRuleType>();
        }
        return this.taxRateRule;
    }

}
