//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:22:41 PM IST 
//


package rispl.jaxb.tax;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GEOCode" type="{}GEOCode_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GEOTaxJurisdiction" type="{}GEOTaxJurisdiction_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TaxAuthority" type="{}TaxAuthority_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TaxableGroup" type="{}TaxableGroup_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TaxGroupRule" type="{}TaxGroupRule_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="FillType" use="required" type="{}FillType_subtype" fixed="KillAndFill" />
 *       &lt;attribute name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Batch" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geoCode",
    "geoTaxJurisdiction",
    "taxAuthority",
    "taxableGroup",
    "taxGroupRule"
})
@XmlRootElement(name = "TaxImport")
public class TaxImport {

    @XmlElement(name = "GEOCode")
    protected List<GEOCodeType> geoCode;
    @XmlElement(name = "GEOTaxJurisdiction")
    protected List<GEOTaxJurisdictionType> geoTaxJurisdiction;
    @XmlElement(name = "TaxAuthority")
    protected List<TaxAuthorityType> taxAuthority;
    @XmlElement(name = "TaxableGroup")
    protected List<TaxableGroupType> taxableGroup;
    @XmlElement(name = "TaxGroupRule")
    protected List<TaxGroupRuleType> taxGroupRule;
    @XmlAttribute(name = "FillType", required = true)
    protected FillTypeSubtype fillType;
    @XmlAttribute(name = "CreationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(name = "ExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationDate;
    @XmlAttribute(name = "Version")
    protected String version;
    @XmlAttribute(name = "Priority")
    protected Integer priority;
    @XmlAttribute(name = "Batch")
    protected Integer batch;

    /**
     * Gets the value of the geoCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geoCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGEOCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GEOCodeType }
     * 
     * 
     */
    public List<GEOCodeType> getGEOCode() {
        if (geoCode == null) {
            geoCode = new ArrayList<GEOCodeType>();
        }
        return this.geoCode;
    }

    /**
     * Gets the value of the geoTaxJurisdiction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geoTaxJurisdiction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGEOTaxJurisdiction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GEOTaxJurisdictionType }
     * 
     * 
     */
    public List<GEOTaxJurisdictionType> getGEOTaxJurisdiction() {
        if (geoTaxJurisdiction == null) {
            geoTaxJurisdiction = new ArrayList<GEOTaxJurisdictionType>();
        }
        return this.geoTaxJurisdiction;
    }

    /**
     * Gets the value of the taxAuthority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxAuthority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxAuthority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxAuthorityType }
     * 
     * 
     */
    public List<TaxAuthorityType> getTaxAuthority() {
        if (taxAuthority == null) {
            taxAuthority = new ArrayList<TaxAuthorityType>();
        }
        return this.taxAuthority;
    }

    /**
     * Gets the value of the taxableGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxableGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxableGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxableGroupType }
     * 
     * 
     */
    public List<TaxableGroupType> getTaxableGroup() {
        if (taxableGroup == null) {
            taxableGroup = new ArrayList<TaxableGroupType>();
        }
        return this.taxableGroup;
    }

    /**
     * Gets the value of the taxGroupRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxGroupRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxGroupRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxGroupRuleType }
     * 
     * 
     */
    public List<TaxGroupRuleType> getTaxGroupRule() {
        if (taxGroupRule == null) {
            taxGroupRule = new ArrayList<TaxGroupRuleType>();
        }
        return this.taxGroupRule;
    }

    /**
     * Gets the value of the fillType property.
     * 
     * @return
     *     possible object is
     *     {@link FillTypeSubtype }
     *     
     */
    public FillTypeSubtype getFillType() {
        if (fillType == null) {
            return FillTypeSubtype.KILL_AND_FILL;
        } else {
            return fillType;
        }
    }

    /**
     * Sets the value of the fillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillTypeSubtype }
     *     
     */
    public void setFillType(FillTypeSubtype value) {
        this.fillType = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBatch(Integer value) {
        this.batch = value;
    }

}
