//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:22:41 PM IST 
//


package rispl.jaxb.tax;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TaxRateRule_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxRateRule_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RateTypeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="Percentage"/>
 *               &lt;enumeration value="Amount"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="TaxAmount" type="{}Amount_type"/>
 *           &lt;element name="TaxPercentageRate">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                 &lt;fractionDigits value="5"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="TaxAboveThresholdAmountFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="TaxAboveThresholdAmount"/>
 *               &lt;enumeration value="TaxEntireAmount"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ThresholdAmount" type="{}Amount_type" minOccurs="0"/>
 *         &lt;element name="TaxRateEffectiveTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="TaxRateExpirationTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="MinimumTaxableAmount" type="{}Amount_type" minOccurs="0"/>
 *         &lt;element name="MaximumTaxableAmount" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxRateRule_type", propOrder = {
    "rateTypeCode",
    "taxAmount",
    "taxPercentageRate",
    "taxAboveThresholdAmountFlag",
    "thresholdAmount",
    "taxRateEffectiveTimestamp",
    "taxRateExpirationTimestamp",
    "minimumTaxableAmount",
    "maximumTaxableAmount"
})
public class TaxRateRuleType {

    @XmlElement(name = "RateTypeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rateTypeCode;
    @XmlElement(name = "TaxAmount")
    protected BigDecimal taxAmount;
    @XmlElement(name = "TaxPercentageRate")
    protected BigDecimal taxPercentageRate;
    @XmlElement(name = "TaxAboveThresholdAmountFlag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String taxAboveThresholdAmountFlag;
    @XmlElement(name = "ThresholdAmount")
    protected BigDecimal thresholdAmount;
    @XmlElement(name = "TaxRateEffectiveTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar taxRateEffectiveTimestamp;
    @XmlElement(name = "TaxRateExpirationTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar taxRateExpirationTimestamp;
    @XmlElement(name = "MinimumTaxableAmount")
    protected BigDecimal minimumTaxableAmount;
    @XmlElement(name = "MaximumTaxableAmount")
    protected BigDecimal maximumTaxableAmount;

    /**
     * Gets the value of the rateTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateTypeCode() {
        return rateTypeCode;
    }

    /**
     * Sets the value of the rateTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateTypeCode(String value) {
        this.rateTypeCode = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxAmount(BigDecimal value) {
        this.taxAmount = value;
    }

    /**
     * Gets the value of the taxPercentageRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxPercentageRate() {
        return taxPercentageRate;
    }

    /**
     * Sets the value of the taxPercentageRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxPercentageRate(BigDecimal value) {
        this.taxPercentageRate = value;
    }

    /**
     * Gets the value of the taxAboveThresholdAmountFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAboveThresholdAmountFlag() {
        return taxAboveThresholdAmountFlag;
    }

    /**
     * Sets the value of the taxAboveThresholdAmountFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAboveThresholdAmountFlag(String value) {
        this.taxAboveThresholdAmountFlag = value;
    }

    /**
     * Gets the value of the thresholdAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getThresholdAmount() {
        return thresholdAmount;
    }

    /**
     * Sets the value of the thresholdAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setThresholdAmount(BigDecimal value) {
        this.thresholdAmount = value;
    }

    /**
     * Gets the value of the taxRateEffectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxRateEffectiveTimestamp() {
        return taxRateEffectiveTimestamp;
    }

    /**
     * Sets the value of the taxRateEffectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaxRateEffectiveTimestamp(XMLGregorianCalendar value) {
        this.taxRateEffectiveTimestamp = value;
    }

    /**
     * Gets the value of the taxRateExpirationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxRateExpirationTimestamp() {
        return taxRateExpirationTimestamp;
    }

    /**
     * Sets the value of the taxRateExpirationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaxRateExpirationTimestamp(XMLGregorianCalendar value) {
        this.taxRateExpirationTimestamp = value;
    }

    /**
     * Gets the value of the minimumTaxableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimumTaxableAmount() {
        return minimumTaxableAmount;
    }

    /**
     * Sets the value of the minimumTaxableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimumTaxableAmount(BigDecimal value) {
        this.minimumTaxableAmount = value;
    }

    /**
     * Gets the value of the maximumTaxableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumTaxableAmount() {
        return maximumTaxableAmount;
    }

    /**
     * Sets the value of the maximumTaxableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumTaxableAmount(BigDecimal value) {
        this.maximumTaxableAmount = value;
    }

}
